### PR TITLE
Support for CSS background-image

### PR DESCRIPTION
**Pull request by dancek**
I needed resizable background-images with dynamic content, so I implemented this. The benefit over a CSS-only solution is that changing an image in code is much easier when you only output one data attribute. I'm not sure if you consider this to be in scope of Slimmage.js, but it made sense to implement it as a feature since Slimmage already has a lot of the required infrastructure.

I have written the code at work, so my employer (HiQ Finland) must be mentioned in the copyright notice. Hopefully this is not an issue.

### CODE REVIEW

**Comment by nathanaeljones** [comment]
v0.3.0 offers `getImageInfo`, similar to how you refactored  `getImageSrcWithWidth`.

It also offers `beforeAdjustSrc` as a callback function, enabling you to include this functionality as a plugin with no downside. slimmage.background.js would be welcome in the repository.

**Comment by dancek** [comment]
Great! I'll try to find time to refactor this and make another pull request.

**Comment by nathanaeljones** [comment]
Ok, thanks. Please include any copyright notices, and make sure you have employer permission to license it as MIT/Apache.

**Comment by nathanaeljones** [comment]
Also, on 0.4.0+, you will want to push any DOM elements you change into the array `window.slimmage.changed`, so that `readyCallback()` can be fired accurately.

**Comment by dancek** [comment]
I wonder if `beforeAdjustSrc` should accept an array of functions instead of a single function. Otherwise plugins would be overwriting each other's callbacks. I'm not sure there will ever be more than one plugin, though -- maybe this can be considered when it actually happens.

**Pull request closed without merging**
