### PR TITLE
Regex fix for using querystring variables starting with "w" or "h"

### PR DESCRIPTION
**Pull request by Jeavon**

### CODE REVIEW

**Comment by nathanaeljones** [comment]
Thanks! Can we add a corresponding unit test? I'll give you push access so you can get full Travis/Sauce tests to work.

**Comment by nathanaeljones** [comment]
They would go in here: https://github.com/imazen/slimmage/blob/master/test/spec/tests.js

**Comment by Jeavon** [comment]
Brilliant, thanks!
Just working on another strange issue with the new getCssValue method not working in Chrome, if I revert it to the v0.2 version it works. Will post further info later

**Comment by nathanaeljones** [comment]
Strange, we [have test coverage for getCssValue](https://github.com/imazen/slimmage/blob/7ff6dbd9d9a02a17e719fa90e2cd153a0fc2fa16/test/spec/tests.js#L233-L246) on a variety of css units ('max-width' property only, though). Unit tests are run on chrome, android 4.0, 4.4, IE6-10, safari, firefox, ios simulator.

**Comment by Jeavon** [comment]
I've added a test, should I push to the unstable branch to get Travis/Sauce to work?

**Comment by nathanaeljones** [comment]
Yes, SauceLabs only works if it's on a real branch. 'unstable' is fine, although more complex stuff should get its own 'features/featurename' or 'bugfix/bugname' branch temporarily until alpha-level, then go into unstable from there.

**Comment by Jeavon** [comment]
Seems like it all worked and passed! Awesome setup!

**Pull request closed without merging**
